baseURL = 'https://venkatmanav.com/'
languageCode = 'en-us'
title = 'Venkat Manavarthi'
enableRobotsTXT = true

[params]
  name = "Venkat Manavarthi"
  fullName = "Venkat Rao Manavarthi"
  tagline = "Software Engineer"
  author = "Venkat Manavarthi"
  description = "Software Engineer specializing in low-latency infrastructure and AI tooling."
  email = "venkatraomanavarthi@gmail.com"
  location = "DC, United States"
  linkedin = "venkatrao-manavarthi/"
  lastUpdated = "2026"
  github = "venkatmanavarthi"